### ISSUE TITLE
Hover states flip-out if page has been scrolled

### ISSUE THREAD

**Issue by JMTyler** [stolksdorf/gifbin#1]
Sometimes a gif set is large enough to require scrolling (such as the [Unknown](http://www.gifbin.biz/buckets/unknown) bucket).

On Chrome, if the page has been scrolled even a tiny amount, the button overlays (gif/gifv link copy & edit) rapidly toggle their visibility while the mouse moves over them.

![Exhibit A](http://i.imgur.com/KxGKanh.gif)

**Comment by stolksdorf** [comment]
Should be fixed in [this commit](https://github.com/stolksdorf/gifbin/commit/91641aa773efc39ed054217c34fd7a45abb42ae6). Let me know and I'll close the issue.

**Comment by JMTyler** [comment]
Weeeee, it's fixed!
